name: alpm
version: '1.0.0'
author: Colin Woodbury
maintainer: colingw@gmail.com
license: BSD3

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds

dependencies:
  - base >= 4.8 && < 4.10
  - bindings-DSL >= 1.0 && < 1.1
  - text
  - versions >= 3.0.1.1 && < 3.1

library:
  source-dirs: .
  extra-libraries:
    - alpm

tests:
  alpm-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -threaded
    dependencies:
      - alpm
      - tasty >=0.11 && <0.12
      - tasty-hunit >=0.9 && <0.10
