name: alpm
version: '0.1.0.0'
author: Colin Woodbury
maintainer: colingw@gmail.com
license: BSD3

ghc-options:
  - -fwarn-unused-imports
  - -fwarn-unused-binds

dependencies:
  - base >=4.9 && <4.10
#  - bindings-DSL >= 1.0 && < 1.1

library:
  source-dirs: .
  extra-libraries:
    - alpm
